//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SegLCD_P4_v1_31 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SegLCD_P4_v1_31.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Files|*.xml.
        /// </summary>
        internal static string CHARS_DIALOG_FILTER {
            get {
                return ResourceManager.GetString("CHARS_DIALOG_FILTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset all changes?.
        /// </summary>
        internal static string CHARS_RESET_MSG {
            get {
                return ResourceManager.GetString("CHARS_RESET_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The 32-kHz watch crystal is not enabled and must be active for use by the LCD Timer..
        /// </summary>
        internal static string CLOCK_XTAL_ERROR {
            get {
                return ResourceManager.GetString("CLOCK_XTAL_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock frequency value was changed. Open the Configure dialog in order to update related parameters values..
        /// </summary>
        internal static string DRC_CLOCK_ERR {
            get {
                return ResourceManager.GetString("DRC_CLOCK_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected number of Commons in the component customizer is greater than max number of Commons supported by the selected device. Open the Configure dialog in order to update related parameters values..
        /// </summary>
        internal static string DRC_NUMBER_OF_COMMONS_ERROR {
            get {
                return ResourceManager.GetString("DRC_NUMBER_OF_COMMONS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected number of Segments in the component customizer is greater than max number of Segments supported by the selected device. Open the Configure dialog in order to update related parameters values..
        /// </summary>
        internal static string DRC_NUMBER_OF_SEGMENTS_ERROR {
            get {
                return ResourceManager.GetString("DRC_NUMBER_OF_SEGMENTS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock frequency is too high to set the correct value of SUBFR_DIV divisor and generate a proper refresh rate.
        /// </summary>
        internal static string EMPTY_FRAMERATE_LIST {
            get {
                return ResourceManager.GetString("EMPTY_FRAMERATE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name cannot be an empty string..
        /// </summary>
        internal static string EMPTY_NAME_MSG {
            get {
                return ResourceManager.GetString("EMPTY_NAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/2 Bias.
        /// </summary>
        internal static string EnumBias_12 {
            get {
                return ResourceManager.GetString("EnumBias_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/3 Bias.
        /// </summary>
        internal static string EnumBias_13 {
            get {
                return ResourceManager.GetString("EnumBias_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/4 Bias.
        /// </summary>
        internal static string EnumBias_14 {
            get {
                return ResourceManager.GetString("EnumBias_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/5 Bias.
        /// </summary>
        internal static string EnumBias_15 {
            get {
                return ResourceManager.GetString("EnumBias_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital correlation.
        /// </summary>
        internal static string EnumDrivingModeDigitalCorrelation {
            get {
                return ResourceManager.GetString("EnumDrivingModeDigitalCorrelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PWM.
        /// </summary>
        internal static string EnumDrivingModePWM {
            get {
                return ResourceManager.GetString("EnumDrivingModePWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High speed.
        /// </summary>
        internal static string EnumLCDModeHighSpeed {
            get {
                return ResourceManager.GetString("EnumLCDModeHighSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low speed.
        /// </summary>
        internal static string EnumLCDModeLowSpeed {
            get {
                return ResourceManager.GetString("EnumLCDModeLowSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type A.
        /// </summary>
        internal static string EnumWaveformTypeA {
            get {
                return ResourceManager.GetString("EnumWaveformTypeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type B.
        /// </summary>
        internal static string EnumWaveformTypeB {
            get {
                return ResourceManager.GetString("EnumWaveformTypeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR_MSG_TITLE {
            get {
                return ResourceManager.GetString("ERROR_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be between {0:G} and {1:G}..
        /// </summary>
        internal static string FORMAT_ERROR_MSG {
            get {
                return ResourceManager.GetString("FORMAT_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value should be an integer between {0:G} and {1:G}..
        /// </summary>
        internal static string FORMAT_INT_ERROR_MSG {
            get {
                return ResourceManager.GetString("FORMAT_INT_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of helpers is {0:G}.
        /// Helper could not be added..
        /// </summary>
        internal static string HELPERS_LIMIT_MSG {
            get {
                return ResourceManager.GetString("HELPERS_LIMIT_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imadd {
            get {
                object obj = ResourceManager.GetObject("imadd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imarrowleft {
            get {
                object obj = ResourceManager.GetObject("imarrowleft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imarrowright {
            get {
                object obj = ResourceManager.GetObject("imarrowright", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imdefault {
            get {
                object obj = ResourceManager.GetObject("imdefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imdelete {
            get {
                object obj = ResourceManager.GetObject("imdelete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imimport {
            get {
                object obj = ResourceManager.GetObject("imimport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imopen {
            get {
                object obj = ResourceManager.GetObject("imopen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imrefresh {
            get {
                object obj = ResourceManager.GetObject("imrefresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imsave {
            get {
                object obj = ResourceManager.GetObject("imsave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap imundo {
            get {
                object obj = ResourceManager.GetObject("imundo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string INFORMATION_MSG_TITLE {
            get {
                return ResourceManager.GetString("INFORMATION_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interconnect.
        /// </summary>
        internal static string InterconnectTabDisplayName {
            get {
                return ResourceManager.GetString("InterconnectTabDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load the alphabet..
        /// </summary>
        internal static string LOAD_TEMPLATE_ERROR_MSG {
            get {
                return ResourceManager.GetString("LOAD_TEMPLATE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough segment and common lines to manage helpers.
        ///Helper could not be added..
        /// </summary>
        internal static string NOT_ENOUGH_SEG_COM_MSG {
            get {
                return ResourceManager.GetString("NOT_ENOUGH_SEG_COM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name {0} is not unique. Enter another name..
        /// </summary>
        internal static string NOT_UNIQUE_NAME_MSG {
            get {
                return ResourceManager.GetString("NOT_UNIQUE_NAME_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected number of Commons is greater than max number of Commons supported by the selected device..
        /// </summary>
        internal static string NUMBER_OF_COMMONS_ERROR {
            get {
                return ResourceManager.GetString("NUMBER_OF_COMMONS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected number of Segments is greater than max number of Segments supported by the selected device..
        /// </summary>
        internal static string NUMBER_OF_SEGMENTS_ERROR {
            get {
                return ResourceManager.GetString("NUMBER_OF_SEGMENTS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decreasing the number of common or segment lines will cause
        ///the loss of pixel mapping information for removed lines.
        /// </summary>
        internal static string NUMLINES_DECREASE_MSG {
            get {
                return ResourceManager.GetString("NUMLINES_DECREASE_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a Template File.
        /// </summary>
        internal static string OPEN_CHARS_TITLE {
            get {
                return ResourceManager.GetString("OPEN_CHARS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the file..
        /// </summary>
        internal static string OPEN_FILE_ERROR_MSG {
            get {
                return ResourceManager.GetString("OPEN_FILE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string PAGE_TITLE_BASIC {
            get {
                return ResourceManager.GetString("PAGE_TITLE_BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Built-in.
        /// </summary>
        internal static string PAGE_TITLE_BUILTIN {
            get {
                return ResourceManager.GetString("PAGE_TITLE_BUILTIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Characters.
        /// </summary>
        internal static string PAGE_TITLE_CUSTOMCHARS {
            get {
                return ResourceManager.GetString("PAGE_TITLE_CUSTOMCHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Helpers.
        /// </summary>
        internal static string PAGE_TITLE_HELPERS {
            get {
                return ResourceManager.GetString("PAGE_TITLE_HELPERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Power Settings.
        /// </summary>
        internal static string PAGE_TITLE_POWERSETTINGS {
            get {
                return ResourceManager.GetString("PAGE_TITLE_POWERSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in committing parameter..
        /// </summary>
        internal static string PARAMETERS_COMMIT_ERROR_MSG {
            get {
                return ResourceManager.GetString("PARAMETERS_COMMIT_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Helpers parameter..
        /// </summary>
        internal static string PARAMETERS_LOADING_ERROR_MSG {
            get {
                return ResourceManager.GetString("PARAMETERS_LOADING_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print error occured..
        /// </summary>
        internal static string PRINT_ERROR {
            get {
                return ResourceManager.GetString("PRINT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during printing..
        /// </summary>
        internal static string PRINT_TABLE_ERROR_MSG {
            get {
                return ResourceManager.GetString("PRINT_TABLE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QUESTION_MSG_TITLE {
            get {
                return ResourceManager.GetString("QUESTION_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove helper functions first..
        /// </summary>
        internal static string REMOVE_HELPERS_MSG {
            get {
                return ResourceManager.GetString("REMOVE_HELPERS_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a Template File.
        /// </summary>
        internal static string SAVE_CHARS_TITLE {
            get {
                return ResourceManager.GetString("SAVE_CHARS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during XML serialization occured..
        /// </summary>
        internal static string SAVE_TEMPLATE_ERROR_MSG {
            get {
                return ResourceManager.GetString("SAVE_TEMPLATE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To assign a pixel, drag it onto the pixel mapping table below..
        /// </summary>
        internal static string TIP_PIXELS_DRAG {
            get {
                return ResourceManager.GetString("TIP_PIXELS_DRAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to use default chars list?.
        /// </summary>
        internal static string USE_DEFAULT_CHAR_LIST_MSG {
            get {
                return ResourceManager.GetString("USE_DEFAULT_CHAR_LIST_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WARNING_MSG_TITLE {
            get {
                return ResourceManager.GetString("WARNING_MSG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to the file..
        /// </summary>
        internal static string WRITE_FILE_ERROR_MSG {
            get {
                return ResourceManager.GetString("WRITE_FILE_ERROR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} has wrong format..
        /// </summary>
        internal static string WRONG_FORMAT_PARAM_MSG {
            get {
                return ResourceManager.GetString("WRONG_FORMAT_PARAM_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name can contain only letters, digits, and &apos;_&apos; symbol..
        /// </summary>
        internal static string WRONG_SYMBOL_MSG {
            get {
                return ResourceManager.GetString("WRONG_SYMBOL_MSG", resourceCulture);
            }
        }
    }
}
